### ISSUE TITLE
macOS: Close button takes multiple clicks to register

### ISSUE THREAD

**Issue by perryprog** [wxMaxima-developers/wxmaxima#1181]
(Created in tandem with #1180)

- macOS only
- Latest stable version of wxMac.
- Latestish master commit (8e251a1)

The close button on either a document or the preferences window takes multiple clicks before it does anything, usually two to three clicks. It does not seem to need to be in succession.

![Document](https://user-images.githubusercontent.com/12972285/70458975-3d505680-1a81-11ea-870d-2ef5bf4614d2.gif)

![Settings](https://user-images.githubusercontent.com/12972285/70459759-d7fd6500-1a82-11ea-8f92-545cad45cebf.gif)

**Comment by gunterkoenigsmann** [comment]
At least I hope that issue is resolved now: When I got a close event the config dialogue decided if that is an "Abort" or an "OK" and didn't veto it - which on Linux is enough for the window to close. Now the config dialogue explicitly forwards the event to the dialogue's parent class, as well.

**Comment by perryprog** [comment]
I (finally) got the devel version of wxwidgets running. This, along with [`b9f1b79`](https://github.com/wxMaxima-developers/wxmaxima/commit/b9f1b79418cae5bbbd066a41d54872417f349a89), seems to make the close buttons work great. It did not seem to fix the issue on stable, but I think that's fine as stable seems rather old for whatever reason.
