### ISSUE TITLE
Demos don't re-center screen anymore, when screen is full. Print also incomplete.

### ISSUE THREAD

**Issue by richardgobeli** [wxMaxima-developers/wxmaxima#1471]
try running demo(tensor);
When the page gets full it will not rewrite the screen with cursor higher up.

I remember this worked years ago.

**Comment by richardgobeli** [comment]
Print also does not work to print out a complete demo section.   It leaves out all of the calculations, because it looks like one big command that overflows the page and gets truncated.

**Comment by gunterkoenigsmann** [comment]
On my computer I believe to see all the calculations. But I found something else:
We try to scroll to the position of the question prompt before we ever have drawn this prompt. ...and the position of objects is only defined after they have ever been drawn. @KubaO : I'll try (as a workaround) to draw cells whose y coordinate isn't known if I try to scroll to them. But there must be a better idea...

**Comment by richardgobeli** [comment]
This does now work OK.
It may be better to position the cursor near the bottom so the last executed commands can still be shown.  This would force a scroll up after each continue command and most past commands can still be seen.
Centering the cursor would clear half of the screen.
Maybe this could be an option in configuration.

**Comment by richardgobeli** [comment]
Please tell me again how to run WxMaxima to get a debug dump.
I am having the program crash when executing a full file, but the file works OK by stepping thru it.
This must be some kind of timing issue.
This same thing happened on the last two days of latest compiled versions.
I need to load some debugger and the start WxMaxima inside the debugger.

**Comment by gunterkoenigsmann** [comment]
The easiest way to do so is to use a suitable `gdb`:

      gdb wxmaxima
      backtrace

**Comment by gunterkoenigsmann** [comment]
With a bit of luck I just have resolved the issue.

**Comment by richardgobeli** [comment]
![image](https://user-images.githubusercontent.com/31253976/105910300-5baf4380-5fee-11eb-93d5-82dd60b7563f.png)
This is the backtrace.
It faulted here:
![image](https://user-images.githubusercontent.com/31253976/105910388-7b466c00-5fee-11eb-989b-ebe6c6b3ae6e.png)
![image](https://user-images.githubusercontent.com/31253976/105913012-e04f9100-5ff1-11eb-9aca-3f298a90bacc.png)

**Comment by richardgobeli** [comment]
this is ok if I stop full calculate after cmetric.
![image](https://user-images.githubusercontent.com/31253976/106076622-8a541980-60d5-11eb-9638-e91c5f2a3295.png)
This is after the stop is after the %i16 line.
![image](https://user-images.githubusercontent.com/31253976/106076699-b5d70400-60d5-11eb-9712-53b7b3d97455.png)
If it is stepped line by line it also works and is readable.

it also get data messed up at other lines now when I calculate the whole file.
![image](https://user-images.githubusercontent.com/31253976/106077030-60e7bd80-60d6-11eb-868e-7e5d932f6b7e.png)
![image](https://user-images.githubusercontent.com/31253976/106077065-6f35d980-60d6-11eb-9635-436d9204de90.png)
The file was always readable before.

**Comment by gunterkoenigsmann** [comment]
That clearly is a missing recalculate. But why?
Resizing the window should fix it temporarily.

---

I think I have half an idea on where the bug might be...

**Comment by richardgobeli** [comment]
I'll try it again in 7 hours.

**Comment by richardgobeli** [comment]
It looks like it is still there in this build from today.
This is weird.  If I execute the whole file, as it processes the file it shows the issue.  But when it is done and I look at the file it looks OK.  So somewhere during the process, it redoes the screen to make it look OK.   But stopping part way thru it looks like below.

![image](https://user-images.githubusercontent.com/31253976/106215756-3e69a900-6197-11eb-8b80-5d3f8a816ac3.png)
![image](https://user-images.githubusercontent.com/31253976/106215720-2c880600-6197-11eb-8c37-ece32ba3fd98.png)

**Comment by richardgobeli** [comment]
It still does not seem to be getting any better.
This version still has issues.
![image](https://user-images.githubusercontent.com/31253976/106350553-b3260b80-629b-11eb-8842-5039a337b904.png)

**Comment by richardgobeli** [comment]
File did not compile last night. 1/31/2021.

**Comment by richardgobeli** [comment]
Is the change you did first for the issue with positioning the screen in a demo causing this problem now for the recalculate?
Maybe the first change needs to done differently so the recalculations are not needed everywhere. 
I hope you are well, you have not been on for a while.

**Comment by gunterkoenigsmann** [comment]
As a father of a 11-days-old son I claim that everything is more than only well ;-) ...and the recalculation issue should be resolved by now: As the layout process costs much time it is always important not to repeat it too often - and if you avoid relayouts it is easy to forget one or two occasions in which they would have been necessary.

In the current case I removed a workaround that tried to use the results of a former layout attempt if we forgot to re-layout a part of the worksheet - which hid, but naturally not resolved some of these errors.

**Comment by richardgobeli** [comment]
Congratulation! That all the time you can. They grow up fast.

**Comment by richardgobeli** [comment]
Printing demos.
Because the printing does not split command lines the demo looks like one line and only prints the first page of the demo.
Would it be possible that when printing a demo line that the print routine goes one level deeper to decide how big a command input and output line is.  This way the whole demo content would be printed as a normal WxMaxima session and after the demo line is over it goes back up one level for printing normal lines again.

**Comment by richardgobeli** [comment]
moved this to #970.
