### ISSUE TITLE
Request for new tag for MacPorts release

### ISSUE THREAD

**Issue by MSoegtropIMC** [wxMaxima-developers/wxmaxima#1498]
Dear wxMaxima Team,

the version on MacPorts is quite old (April 2020) - mostly because some serious Mac specific issues took a longer time to track down and fix.

The master version of a week back looks much very nice, though. Can we have a tag soon so that I can make a new MacPorts release or is there something blocking a new release? In the latter case it would be good to have a schedule - I might want to make an intermediate release based on a commit hash then until the tag is ready.

**Comment by daute** [comment]
I released a new wxMaxima version now (tagged with `Version-21.02.0`).
Thanks for creating the Mac release!

Best regards, Wolfgang

**Comment by MSoegtropIMC** [comment]
Perfect, thanks! I will build and test this release for a few days and then do the MacPorts release mid/end of this week.

**Comment by MSoegtropIMC** [comment]
@miccal : FYI: I just created a PR on MacPorts to update to version 21.02.0.

Please note that you should remove any OMP build options in Homebrew, but afaik you anyway didn't have this. The code was recently changed to use std c++ threads.

The issue (https://github.com/wxMaxima-developers/wxmaxima/issues/1441) is not yet fixed on MacPorts, but I released it anyway and included instructions for a work around in the post install notes. Is this already fixed on Homebrew?

**Comment by gunterkoenigsmann** [comment]
One issue is currently in the process of being dealt with: https://gitlab.kitware.com/cmake/cmake/-/issues/21566#note_913600

**Comment by gunterkoenigsmann** [comment]
With big Sir being around which doesn't like unsigned binaries: would it make any sense at all if I instructed github actions to automatically generate a wxmaxima.dmg on each new release?

**Comment by MSoegtropIMC** [comment]
@gunterkoenigsmann : the bug you linked above might be a bug in XCode, which is fixed meanwhile. Updating XCode might fix this. The symptoms in (https://trac.macports.org/ticket/62348) and (https://trac.macports.org/ticket/61933) are similar.

MacPorts and Homebrew seem to work fine with BigSur (besides the mentioned XCode bug). But having a .dmg package is definitely also an important and useful way to install wxMaxima on Mac. If you have something, please let me know, so that I can test it (I also have access to BigSur machines).

Btw.: for BigSur it is not uncommon to have machines with ARM CPU. They can emulate intel code, but it might make sense to look into that for stuff which includes a compiler like Maxima.

**Comment by gunterkoenigsmann** [comment]
Ok... ...wxMaxima can now be compiled on the mac and the .dmg installer github creates after each commit contains both an intel and a arm binary. What I now have to find out is how to tell github actions to upload this installer to a release: We already do so with the .exe installer for windows. But I have no idea on how not to make the other installer an entirely new release. I hope switching the release uploader to https://github.com/marketplace/actions/github-release-create-update-and-upload-assets will resolve that problem.

**Comment by daute** [comment]
@MSoegtropIMC: Thanks a lot.

Can you help to clarify https://github.com/wxMaxima-developers/wxmaxima/issues/1469 and the build instructions for MacOS in Compiling.md (https://github.com/wxMaxima-developers/wxmaxima/blob/master/Compiling.md) and the MacOS related links and instructions on our website https://wxmaxima-developers.github.io/wxmaxima/download.html ?
