### ISSUE TITLE
Problem of Subscript display after Version 19.X

### ISSUE THREAD

**Issue by idealkindom** [wxMaxima-developers/wxmaxima#1713]
I found that after version 19.X,wxMaxima has introduced some problem of subscript display.
Since no pics are allowed to upload.I give the "text" in a wxmx file as folow:

 wxsubscripts: 'all$
ΔP_r;print('ΔP_r,"=",4.6,".")$
 ΔP_r1;print('ΔP_r1,"=",2.3,".")$
ΔP_r[1];print('ΔP_r[1],"=",x,".")$

The outputs in In wxMaxima 22.03 and wxMaxima 19.05.7 are quite different concerning the display of subscripts, among which the unintended outputs contain "_".

If you remove "wxsubscripts: 'all$" in input scripts the output results vary.

**Comment by gunterkoenigsmann** [comment]
I believe that issue should be resolved now.

**Comment by idealkindom** [comment]
> I believe that issue should be resolved now.

So, please, what version of WxMaxima are you using now? Did you try the "txt" I pasted above to a wxmx file and run to see the ouputs?

**Comment by gunterkoenigsmann** [comment]
I always use the nightly build - and I did try the .txt file.

**Comment by idealkindom** [comment]
> I believe that issue should be resolved now.

Hi, today I tried nigtly buit Maxima with latest WxMaxima version on a Windows 10 PC, since after Maxima 5.46 it looks like that Win 7 is no longer supported. To my dissapointment, after trying what I listed before in WxMaxima and run, the subscript display problem still exists.
