### ISSUE TITLE
Trying to find a working tag for a new MacPorts release

### ISSUE THREAD

**Issue by MSoegtropIMC** [wxMaxima-developers/wxmaxima#1802]
@ryandesign and me are currently trying to create a new MacPorts version. I tried the latest 3 tags and all have very severe issues:

## 2023.05.1:

- the help system does not seem to work except for displaying help in the sidebar
  - if show help in browser is selected, it is also shown in side bar
  - if show help in console is selected, nothing happens or it is also shown in sidebar (seems to depend on history)

- the cursor navigation is broken. Most of the time when cursor left or cursor right is pressed, the cursor does move internally, but the displayed cursor does not move. This effect is a bit modal and sometimes it does work, but mostly it doesn't (e.g. after evaluating a cell with Shift+Enter)

- setting the cursor with the mouse also has some odd effects, e.g. when I click at the end of the document to set the cursor there, it goes to after the first cell.

- CMD+C copy of Maxima code does not work (menu edit copy does work, CMD+V does work)

## 2023.07, 2023.08

It is very hard to say something about these two versions because in these versions it takes 30..40 seconds to start up a maxima session. This happens for each new document and each open. As far as I can tell the cursor issues are gone, but cause of the delay I didn't test it much.

## Summary

Can we have a patch of 2023.08 where whatever has changed from 2023.05.1 in maxima session management is undone or fixed?

Btw.: the long term issues with the preferences dialog seem to be fixed in 2023.05.1

## Open Tasks

- [x] https://github.com/wxMaxima-developers/wxmaxima/issues/1820
- [x] https://github.com/wxMaxima-developers/wxmaxima/issues/1821
- [x] https://github.com/wxMaxima-developers/wxmaxima/issues/1822
- [x] https://github.com/wxMaxima-developers/wxmaxima/issues/1837
- [x] https://github.com/wxMaxima-developers/wxmaxima/issues/1838
- [x] https://github.com/wxMaxima-developers/wxmaxima/issues/1839
- [x] https://github.com/wxMaxima-developers/wxmaxima/issues/1841

**Comment by MSoegtropIMC** [comment]
One more note on the help system in 2023.05.1:  "Show help in console" seems to be the default, which does not make a lot of sense on Mac since one doesn't start it from a console, so there is none (and I don't think it makes a lot of sense on other platforms either)

**Comment by MSoegtropIMC** [comment]
@gunterkoenigsmann : should I try to bisect the start up time issue or do you have an idea what this can be? The help menu stuff should be easy enough to fix.

I used the 2023.08.0 version the last days and besides the issues I mentioned above I couldn't find anything (but did only usual work so far - no dedicated tests).

**Comment by gunterkoenigsmann** [comment]
If you were willing to do that, that would be great!
On Windows and Linux I *thought* that start-up time has increased by a fraction of a second when we stopped to compress the built-in svg images. But that was a) not logical and b) a fraction of a second on a very slow processor.

The help system issue lies in maxima, but I didn't manage to tell the maxima team what is amiss and I believe I can find a workaround.

Currently I am trying to resolve hundreds of warnings from static analysis tools: That was what made the config dialogue issues go away. Let's hope that it fixes more bugs than it creates...

**Comment by MSoegtropIMC** [comment]
Static analysis sounds good - in my experience it can lead to a few hickups initially but is very worthwhile in the long run.

I will do a bisection of the startup time issue on Mac.

**Comment by gunterkoenigsmann** [comment]
Thanks a lot

What gave me a fright was the time EditorCell.cpp needed a >400 line fix in order to get rid of a few warnings. And that coverity-scan at first complained about every fix I did for the msvc analysis tool. But it seems if they are both happy at the same time that is a good sign.

**Comment by gunterkoenigsmann** [comment]
Ok... ...the static analysis tools are happy now:
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/5041537/7eaed56f-61c9-4e3d-a6b2-39c0d2ce0adf)
Let's hope that this is a good sign.

**Comment by MSoegtropIMC** [comment]
I plan to do the bisection early afternoon today. I will first try latest, and if this does not work bisect.

**Comment by gunterkoenigsmann** [comment]
Perhaps the "debug messages" sidebar gives some insight. Not that the problem is something like an endless loop if links in a directory wxMaxima searches on startup or something similar ...

**Comment by MSoegtropIMC** [comment]
@gunterkoenigsmann : I found some time to do the bisection. Here are my notes around the point where it happens. So the startup issues started with commit 7d7026393bfbc277ed0299478d156101dd46f254 (A wild guess on what makes the cursor disappear for some users)
```
commit 819453bf39400a34716d540f820af200c6c95d5c
bisect-271: build OK, slow startup
Author: Gunter Königsmann <gunter@peterpall.de>
Date:   Tue Jul 4 01:44:53 2023 +0200

    Code simplification

commit 3cc8a94c7da3cbb09d4b293b88e734666da596e2
bisect-272: build OK, slow startup
Author: Wolfgang Dautermann <dauti@users.sourceforge.net>
Date:   Sun Jul 2 11:18:08 2023 +0200

    Manual: document, that wxplot_size works for many embedded plotting functions.

commit 7d7026393bfbc277ed0299478d156101dd46f254
bisect-273: build OK, slow startup
Author: Gunter Königsmann <gunter@peterpall.de>
Date:   Thu Jun 29 23:06:27 2023 +0200

    A wild guess on what makes the cursor disappear for some users

commit 5604eee1fcfa2aa06a5af94f9b5625c4cb35551f
bisect-274: builds OK, startup OK, issues loading plots from wxmx file
Author: Gunter Königsmann <gunter@peterpall.de>
Date:   Sun Jun 25 08:56:52 2023 +0200

    Tried to reinstate the EditorCell optimizations

commit 2e2ba8cf34f8ed90b19873e3774211be6462bc2f
bisect-275:
Error: Failed to build wxMaxima: command execution failed
Error: See /opt/local/var/macports/logs/_Users_msoegtrop_MacPorts_macports-local_math_wxMaxima/wxMaxima/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets if you believe there is a bug.
Error: Processing of port wxMaxima failed
Author: Gunter Königsmann <gunter@peterpall.de>
Date:   Sun Jun 25 08:29:05 2023 +0200

    Removed a lock that didn't help

commit 5d8592af967810013cae2c769854605a2c4e7847
bisect-276
Error: Failed to build wxMaxima: command execution failed
Error: See /opt/local/var/macports/logs/_Users_msoegtrop_MacPorts_macports-local_math_wxMaxima/wxMaxima/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets if you believe there is a bug.
Error: Processing of port wxMaxima failed
Author: Gunter Königsmann <gunter@peterpall.de>
Date:   Sun Jun 25 08:25:54 2023 +0200

    That lock didn't work as it should have
```

**Comment by MSoegtropIMC** [comment]
P.S.: main does not destroot (means it builds, but does not produce an installable app):
```
commit af1a0a9bb50fe53fae70a9a7c3c91472f3c5664e (HEAD -> main, origin/main)

bisect-1: Error in destroot
Error: Failed to destroot wxMaxima: error copying "/opt/local/var/macports/build/_Users_msoegtrop_MacPorts_macports-local_math_wxMaxima/wxMaxima/work/build/src/wxmaxima.app": no such file or directory
Error: See /opt/local/var/macports/logs/_Users_msoegtrop_MacPorts_macports-local_math_wxMaxima/wxMaxima/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets if you believe there is a bug.
Error: Processing of port wxMaxima failed

Author: Gunter Königsmann <gunter@peterpall.de>
Date:   Sun Sep 17 08:15:38 2023 +0200

    cppcheck and coverity-scan warnings
```

**Comment by MSoegtropIMC** [comment]
P.P.S.: as mentioned 23.08 does build.

**Comment by gunterkoenigsmann** [comment]
If it doesn't build to destroot that should mean that earlier in the build process there was some error when creating "/opt/local/var/macports/build/_Users_msoegtrop_MacPorts_macports-local_math_wxMaxima/wxMaxima/work/build/src/wxmaxima.app". Could you send me the full build log? My hope is that that error produces an error message, somewhere.

**Comment by gunterkoenigsmann** [comment]
If CMD+C copy is broken my guess is that in wxMaximaFrame.cpp the line
````
  APPEND_MENU_ITEM(m_EditMenu, wxID_COPY, _("&Copy\tCtrl+C"),
                   _("Copy selection"), wxS("gtk-copy"));
````
is broken. The only way for it to break is that in the language wxMaxima uses on your system the translation of `&Copy\tCtrl+C` is broken, somehow...

**Comment by gunterkoenigsmann** [comment]
In the log from compiling wxMaxima on github actions (https://github.com/wxMaxima-developers/wxmaxima/actions/runs/6209454448/job/16856674735) I see the line
````
[113/113] Linking CXX executable src/wxmaxima.app/Contents/MacOS/wxmaxima
````
That should be the file that is missing in your case. Afterwards it looks like that file is somehow modified by the 
````
sudo make install
````
that follows.

**Comment by MSoegtropIMC** [comment]
@gunterkoenigsmann : I tried latest master (05389e057c8bc7f9cc1fd706469030c5dee6b7e1):
- it builds
- the startup time issue seems to be gone

I will test this version for a few days and then you should tag and I do a release.

**Comment by MSoegtropIMC** [comment]
@gunterkoenigsmann : what still doesn't work (well) is opening a wxmx file which contains plots - I get an error message:
```
can't open file 'maxout_18876_1.gnuplot' (error 2: No sch file or directory)
```
for each plot in the file.

**Comment by gunterkoenigsmann** [comment]
Could you send me such a file? 

IAM extremely busy for the next two weeks, but I will do what I can.

**Comment by gunterkoenigsmann** [comment]
Tested it again. Somehow I find no way to trigger this bug on my computer. But I have just resolved a bug with respect to saving .wxmx files. There is a (very) remote chance that it is the one you encountered.

**Comment by MSoegtropIMC** [comment]
@gunterkoenigsmann : OK, I will test it.

In the commit I mentioned before, after some testing, these things don't work:
- the errors on load
- Copy + paste of pieces of text - copy and paste of complete cells seems to work
- If a computation produces a larger result (I have a nested struct which prints about 50 lines or so), I can't scroll to the bottom any more. When I resize the Window (or drag the separator to the side bar) it works.

**Comment by MSoegtropIMC** [comment]
The Ctrl+C Ctrl+V stuff I think has nothing to do with keys not working - I  now believe it either works with shortcuts and menues or neither, but it is highly modal. All Copy options are frequently grayed out in the menu.

**Comment by gunterkoenigsmann** [comment]
That is a good hint on where to look! Thanks a lot!
In the meantime I have found out how to make Github test if the program can be compiled on MacPorts for every commit to the core repository as to prevent bit rot.

**Comment by gunterkoenigsmann** [comment]
Just corrected a potential issue with enabling the menu items. If the Ctrl+C still doesn't work that would mean, that wxMaxima knows how to determine when copying should work, but that function isn't triggered when it needs to. I would be surprised, though, if the problem resised there.

**Comment by gunterkoenigsmann** [comment]
The scrolling Issue I will hunt down and find. But for the loading Issue I am at a complete loss where it could reside and I seem not to be able to reproduce it on my linux box => either I am doing the wrong thing for testing or the mac does something different to what my linux box does.

If you could provide me with a file with the loading error I hope that makes hunting down that bug easier.

**Comment by gunterkoenigsmann** [comment]
For the worksheet height issue I am afraind I need some help reproducing that, too:
````
(%i1)	e;
(%i2)	makelist(i,i,1,10000);
````
doesn't allow me to reproduce the bug.

**Comment by MSoegtropIMC** [comment]
I see that i can prepare test files for the loading and the scrolling issue - it might take until Thursday.

**Comment by gunterkoenigsmann** [comment]
I am currently trying to replace the code that loads the images from the wxmx file: currently I tell the images' URLs to wxFileSystem, which causes problems when the path to the file contains spaces and/or non-ascii stuff that the URL-encoder/decoder gets wrong. But there nowadays is a second method that works with file names. Perhaps it makes sense to test once I have applied that change

**Comment by MSoegtropIMC** [comment]
@gunterkoenigsmann : one observation from daily use: the scoll area issues seems to happen if a command produces a lot of print output (> 1 screen page or so) and then a lot of output (in my case usually wxDraw2D graphics).

**Comment by gunterkoenigsmann** [comment]
Ok... ...the image loading issue might have changed with completely changing the way images are loaded from wxmx in aa97209d461354b4699e08b85f6338d42b381068

Will tomorrow look if the size of images is calculated correctly only after the worksheet size has been recalculated. Perhaps that is the other issue...

**Comment by gunterkoenigsmann** [comment]
Ok... ...found a way to reproduce the scrolling issue:
````
for i:1 thru 300 do disp(j);
wxdraw2d(explicit(sin(x),x,1,100));
````

**Comment by gunterkoenigsmann** [comment]
The problem doesn't appear if the wxdraw2d is missing.

**Comment by gunterkoenigsmann** [comment]
Ok... ...with a bit of Luck the scrolling issue is resolved now.

**Comment by MSoegtropIMC** [comment]
Many thanks! I am OOO today and will try the latest commit tomorrow.

Should the Ctrl+C/Ctrl+V issue also be solved (I lost track a bit - maybe I should create separate issues ...).

**Comment by gunterkoenigsmann** [comment]
I have rewritten the logic that decides if to enable the copy menu entry. If it still doesn't work that would mean we don't call that logic when we should, but that would really surprise me as we call it every time wxMaxima's event queue is empty.

**Comment by MSoegtropIMC** [comment]
@gunterkoenigsmann : I built the latest version (that is 2790fdb476cb15656f56f0ca8f17a7b2644b8dab) and all looks fine. Ctrl-C, Ctrl-V works, scrolling issues gone, loading of wxmx files with plots OK and the connect slowness is already fixed before. So this commit looks good to go. Let me test it until mid of next week and then I would ask for a tag (for exactly this commit).

**Comment by MSoegtropIMC** [comment]
@gunterkoenigsmann : I went again through my check list and what still does not work is help. Regardless of what I set the display help setting in the help menu to, I get the help in a panel (which is so small that this is hardly useful). Sure I could make it larger but I really don't like this. I find it much easier to work with help in a browser. For Ubuntu the panel reader might be useful, though, since the Ubuntu team managed to mess up Firefox in such a way that it can't open local files any more (snap sandbox).

**Comment by gunterkoenigsmann** [comment]
Wow... ...then loads of thanks for all the testing, debugging and persistence that has made this possible. And the web browser is really messed up, on Ubuntu. 
The way around this would be: 

- Making a maxima snap
- Maximg a wxMaxima snap that contains wxmaxima plus all libraries wxMaxima needs, the contents of the maxima snap and the contents of all the snaps browsers are shipped in. That would still not allow to combine maxima help tabs with browser tabs from a browser that was started separately and would make wxMaxima more than one Gigabyte long. But it would add a sandbox around the whole thing and therefore improve security, which is essentially the same as Electron apps under Windows.

I am curious to see what we will say about such constructs ten years from now. But today I am still unsure if that is a good idea...

**Comment by gunterkoenigsmann** [comment]
The browser panel I added because I first thought that it would be easy to do so - and then started to like it, especially on Ubuntu, as you already guessed, and, because it doesn't open every help chapter in its own browser tab. What I still am unsure about is: Currently the help viewer can be configured using a maxima variable. Do we want wxMaxima to configure this variable for us on starting maxima remembering the last setting the user chose - and what would be sane defaults?

If I understand you right on the mac perhaps the standalone browser would make sense. On Ubuntu a wxMaxima browser tab - and on Windows I would prefer a browser tab, as well, as I know many users who liked that tab.

**Comment by MSoegtropIMC** [comment]
My pleasure :-) I say thank you for the quick support!

Regarding help: I still think the browser should be default or the tab should have a reasonable default size. As is, it is almost so small, that one doesn't realise that the help opened in it, so people might believe that the help menu is not functioning correctly.

The main issue I have is that on Mac is different, though. it is that the setting (console, panel, browser) doesn't do anything at all. Whatever I choose, I get the help in the panel. This must be fixed. What is the default is then a secondary question.

**Comment by MSoegtropIMC** [comment]
Regarding snap: I don't like it very much either - the security overhead is very high and if this makes a lot of sense in a system where one can install .deb packages as well is a good question. But it is used, and in this sense it is useful.

**Comment by gunterkoenigsmann** [comment]
I actually understand that you want to sandbox applications. But if your browser can read your files, has access to the web and can place files in your autostart folder the sandbox hinders you from working whilst not preventing many attack scenarios...

**Comment by MSoegtropIMC** [comment]
Yes, the firefox sandboxing on Ubuntu is questionable.

Anyway: how about Mac: as I said the real issue is that the selection of help display does not work. Regardless what I set there, the output always ends up in the panel.

**Comment by gunterkoenigsmann** [comment]
Ok ... The browser tab has now a default size > 0, it is more obvious now that wxMaxima had its own configuration item for the help browser and Maxima's help browser setting now is persistent. And as one of the bug fixes you requested caused the intermittent issues with the self test on GitHub actions to be persistent I managed to fix that bug, too.

**Comment by gunterkoenigsmann** [comment]
For me that commit reverts the zoom factor on right-click -> more bug fixing to do; when I suspected that you interpreted the menu item wrong I added additional menu entries for clarification: my guess is if you are misled many others will be, too.

**Comment by gunterkoenigsmann** [comment]
I believe 7346ab87230e30c01335a90c877e110090344021 should be a good commit to make a tag.

**Comment by MSoegtropIMC** [comment]
Sure, I can test this commit - it is only one after the one I tested so far.

**Comment by gunterkoenigsmann** [comment]
The difference is: If you try to handle pinch zoom events on windows and Linux current wxWidgets versions interpret right -clicks as zoom events => disabled the pinch zoom handler.

**Comment by gunterkoenigsmann** [comment]
Ok. Made a tag. Difference between the tag and that commit:

- The version number
- The ChangeLog
- The AppData file that isn't used by wxMaxima, but might be read by the package manager of certain linux distributions.

**Comment by gunterkoenigsmann** [comment]
As always the moment I make a release bad bugs are found => added commits 2240ae5af2194eb6764321f8098b1a96a469d723 and 5688eac7b8299e0164762bacbba5775364ca389c. The question now is when to make a new tag/release?

**Comment by MSoegtropIMC** [comment]
@gunterkoenigsmann : I didn't du much testing as yet. I regularly do Maxima stuff in the commuter train, but I was not in office last week. I expect to do quite a bit of testing until Thursday. Let's do the tag after testing.

**Comment by gunterkoenigsmann** [comment]
....and after I have fixed the bug that makes copying items as images unreliable.

**Comment by MSoegtropIMC** [comment]
FYI.: I am testing 9ad8fba4b2817038844146d3681d66ba20adb4e5 today.

**Comment by MSoegtropIMC** [comment]
@gunterkoenigsmann : I found one issue: if I select some text, say an identifier by double clicking on it, and then type to replace it, the curser wents somewhere else and types there. It might be that the curser ends up at the character count of the end of the selected regeion before it was deleted. Say if I select a 15 char identifier and type, I think the curser us 15 chars behind the position it should be.

**Comment by MSoegtropIMC** [comment]
@gunterkoenigsmann : starting nitpicking: what would be really nice is if the find & replace dialog (Ctrl+F) would focus the find text field by default. This might be editable in the dialog editor.

**Comment by gunterkoenigsmann** [comment]
I am currently trapped in real live (tm). But I've updated the original description of this issue with a checklist of things we definitively want to fix and I do plan not to change anything that isn't a bug fix or a translation update until we have a working release. In order to make sure that nothing gets lost I've additionally split the new findings into separate issues the checklist references.

**Comment by gunterkoenigsmann** [comment]
> @gunterkoenigsmann : starting nitpicking: what would be really nice is if the find & replace dialog (Ctrl+F) would focus the find text field by default. This might be editable in the dialog editor.

That's exactly the kind of report that helped making wxMaxima streamlined enough that it can be fun working with it.

**Comment by gunterkoenigsmann** [comment]
Ok... ...the issues you have reported should now finally be resolved. The next task I plan to do is a big rewrite of the copy functionality that will take place in a branch.

**Comment by gunterkoenigsmann** [comment]
Added a few additional bug fixes to the main branch - and replaced many instances of `operator[]` by at(), as that adds range checking: Perhaps that makes subtle bugs visible.

**Comment by MSoegtropIMC** [comment]
OK, I will do a new build today and test it - I didn't have time to test the status from last Wednesday.

**Comment by MSoegtropIMC** [comment]
@gunterkoenigsmann : I didn't use wxMaxima the last 3 weeks much, so didn't do much testing (actually using it is the best test). I will use it more this week, so I tried the latest commit 9903c2b750ab112ed64dd666ad7f314219f31db7.

It looks pretty good! One minor thing: If I load a file, select a piece of text and type the text is now properly replaced. Only the Undo meno entry is not enabled. The undo entry is there, though. If I do another edit (insert text so that a new cell is created), undo works for the second and the first edit. So apparently it is just a question of enabling the menu entry.

This is a rather benign issue, since it rarely happens (only if an overwrite edit is the first thing one does, and one wants to undo it right away), so I would be fine with using this commit. Of course if you want to fix it, I would take that commit - as you prefer.

**Comment by gunterkoenigsmann** [comment]
Added all known issues that I want to fix before the new release to the checklist above

**Comment by MSoegtropIMC** [comment]
OK - please ping me when these issues are fixed. I keep using the commit from yesterday in my daily work.

**Comment by gunterkoenigsmann** [comment]
Ok... ...I believe the last 3 issues should be resolved by now.

**Comment by MSoegtropIMC** [comment]
Thanks, I make a quick test ...

**Comment by MSoegtropIMC** [comment]
I just tested 2af2a482b3570414a75b3f0d802c4b3eb5d24318.

Two items from the list don't work for me:

- enabling of the undo button. I am doing the following: open existing file, select some text by drag with mouse, type one letter => Edit / undo is not enabled
- the focussing of the search field in the file search dialog doesn't work any more - afair this did work in a previous test.

**Comment by gunterkoenigsmann** [comment]
Didn't manage to understand the undo function. But managed to write a new one. Hope it resolves all issues - and the focussing issue might be a timing issue => moved the activation command to after the focus event that possibly involves activating an item after I tried to activate it and did the same for all commands that activate the worksheet.

**Comment by MSoegtropIMC** [comment]
@gunterkoenigsmann : I tested wxMaxima a bit now and it is really good now.

There is one issue, though, with the regexp search. While entering a regexp I sometimes get a pop up dialog stating that the regexp is invalid (which is a very common intermediate situation when entering the regexp). Usually it just colors the edit field orange, but sometimes the pop up comes and on closing this popup Maxima crashes. I couldn't nail down when the pop up comes, though. It usually comes only after  working for a while, but then regularly. In testing after a fresh start it is hard to reproduce. Maybe you can make sense out of it ... If not it shouldn't stop us from releasing.

**Comment by gunterkoenigsmann** [comment]
Ok... ...repaired the backwards and regexp search.

**Comment by gunterkoenigsmann** [comment]
...and wxMaxima now asks wxWidgets to provide a meaningful backtrace on crashes, if all the neccessary info and functionality is available.

**Comment by MSoegtropIMC** [comment]
Perfect timing - the last 2 weeks I had no opportunity to test it, but this week I plan to use wxMaxima a lot!

**Comment by gunterkoenigsmann** [comment]
Ok... ...@daute and me have once again resolved a big bunch off issues so I would be willing to create another release - but there is an issue that maybe needs checking beforehand: #1777 feels a bit like if once wxMaxima has changed the path of maxima to the current folder of the worksheet maxima no more knows where to find its share libraries. My guess is that that is no issue for macPorts.

**Comment by gunterkoenigsmann** [comment]
Ok... ...printing now works flawlessly and doing so caused many visual glitches in the worksheet t disappear. But arriving at this point was a big change => no idea if this has introduced new bugs...

**Comment by MSoegtropIMC** [comment]
Thanks, I will give it a try today - I didn't test much the begin of Dec version - too busy with other things, but it did basically look fine.

**Comment by MSoegtropIMC** [comment]
@gunterkoenigsmann : I have tested commit 4d312b48e05c6ac85fa23c74724034f1434f7caf from yesterday a bit. It looks OK, but one issue is that spacing in the editor, especially around assignment colons as in 'x : 3;' gets completely messed up when changing the zoom in any way.

**Comment by MSoegtropIMC** [comment]
@gunterkoenigsmann : I just tried commit fc52b7dec2c286cacdcd162592e14a07efd9fd61 from Dec 22 (from your previous post) and zooming doesn't completely mess up things there, but it doesn't zoom font size - the spacing gets larger but the letters stay the same size.

**Comment by MSoegtropIMC** [comment]
P.S.: commit 2af2a482b3570414a75b3f0d802c4b3eb5d24318 from Nov 15th - which I tested quite a bit - doesn't have the zoom issue, but the two (rather minor) issues I mentioned above. For me it would be OK to use this commit as a release for Mac - the issues are relatively minor compared to later commits.

**Comment by gunterkoenigsmann** [comment]
That commit had, according to the test suite, still random crashes when multiple windows were opened by the same process - and many of the checkmark menu items didn't work. But the info about the issue on zooming was important. With commit cb1468adaf4168031bf8a5d0317e22313a6bbbdf I have managed to resolve this one. Thanks for reporting it!

**Comment by MSoegtropIMC** [comment]
@gunterkoenigsmann : thanks! I can confirm that in cb1468adaf4168031bf8a5d0317e22313a6bbbdf the zoom issues (both bad spacing scaling and lack of font scaling) are fixed.

I will test this for some days.

**Comment by MSoegtropIMC** [comment]
@gunterkoenigsmann : I now tested cb1468adaf4168031bf8a5d0317e22313a6bbbdf for a while and I would say it is good for a release, so could you please tag it?

It sometimes happens that it is hard to place the cursor at the end of the document - one then has to click quite precisely below the last cell and clicking into the white space below it won't position the cursor at the end of the file as it ususually does. But I couldn't figure out when thuis happens. It is a state thing - when it does happen, it is reproducible until I reopen the file. But I wouldn't block a release cause of this minor issue.

Thank you for all the good work and fixes!

In the future I would appreciate if you would send me about every 3 months a request to test a tag, say via a test request issue here where you CC me (and maybe a few others).

**Comment by MSoegtropIMC** [comment]
@gunterkoenigsmann : is it possible to get a tag for the commit I tested?

**Comment by gunterkoenigsmann** [comment]
Everything is good if it helps updating wxMaxima on MacPorts.

**Comment by gunterkoenigsmann** [comment]
Release 24.01.0 is made of the commit you tested.

The only thing I have fixed in 24.02.1 that might be worth testing: Under Ubuntu 24.01.0 crashed if i opened a second wxMaxima window and then closed it again.

**Comment by MSoegtropIMC** [comment]
Thanks, I will look into it.

**Comment by MSoegtropIMC** [comment]
@gunterkoenigsmann : I thought I would have opportunity to test 24.02.1, but didn't so I am going to release 24.01.0 (I don't see issues starting multiple wxMaxima instances).

There is only one odd thing: in the wxMaxima about box it says "wxmaxima 23.12.0 Development scnapshot".

**Comment by gunterkoenigsmann** [comment]
If it works I guess it is a good version to make a release of.

About the "about dialogue": Thanks for the info. Will try to find out what is going on here.

**Comment by MSoegtropIMC** [comment]
> If it works I guess it is a good version to make a release of.

The only thing I found is that sometimes I cannot place the cursor at the end of the document (below the last cell). A recompute usually fixes this. But I couldn't find out yet when this happens.

> About the "about dialogue": Thanks for the info. Will try to find out what is going on here.

Should I wait for a fix or release it as is?

**Comment by MSoegtropIMC** [comment]
@gunterkoenigsmann : I am still waiting for an answer to:

> > About the "about dialogue": Thanks for the info. Will try to find out what is going on here.
> 
> Should I wait for a fix or release it as is?

**Comment by gunterkoenigsmann** [comment]
Release: Fixing this bug is enough code changes that it will likely create new ones.

**Comment by MSoegtropIMC** [comment]
OK, I will trigger the release.

Thanks a lot for all the support!
