### ISSUE TITLE
Producing string with newline

### ISSUE THREAD

**Issue by andrejv** [wxMaxima-developers/wxmaxima#76]
Converted from [SourceForge issue 2821689](http://sourceforge.net/support/tracker.php?aid=2821689), submitted by m-h-s

In command-line maxima, a string can contain newline characters, e.g. the following works:
teststring: "this 
is a 
string"

preserving the newlines. wxMaxima behaves differently, and removes the newlines.

**Comment by gunterkoenigsmann** [comment]
I *think* I found the reason which comes in two parts:
 - xml by default ignores literal newlines and wants them to be escaped as &#13;
 - wxMaxima didn't handle newlines in strings, either. But I tried to change that and if we are lucky it does do so by now.
I would need help for the xml part, though: wxMathml.lisp still needs to be modified to escape newlines.

**Comment by gunterkoenigsmann** [comment]
Did try 

     (defun wxxml-fix-string (x)
       (if (stringp x)
           (let* ((tmp-x (string-substitute "&amp;" #\& x))
     	     (tmp-x (string-substitute "&lt;" #\< tmp-x))
     	     (tmp-x (string-substitute "&gt;" #\> tmp-x))
     	     (tmp-x (string-substitute "&#13;" #\return tmp-x))
     	     (tmp-x (string-substitute "&#13;" #\linefeed tmp-x))
     	     (tmp-x (string-substitute "&#13;" #\newline tmp-x)))
     	tmp-x)
      x))

Why does this fail to work?

**Comment by gunterkoenigsmann** [comment]
Ok... ...the issue was in the xml parser and is resolved by now.

**Comment by robert-dodier** [comment]
I am working with wxMaxima 20.07.0 for macOS which I obtained from https://github.com/wxMaxima-developers/wxmaxima/releases , where it is apparently the most recent binary release for macOS.

I'm still seeing this problem with inputs such as
```{text}
"this
is
a
string";
```
which displays `thisisastring`,
and 
```{text}
printf (false, "foo~%bar~%");
```
which displays `foobar`.

Note that `printf(true, "foo~%bar~%");` does display output on two lines as expected.

`:lisp (trace wxxml-fix-string)` shows that the newline characters are detected and replaced with XML entities:
```{text}
  0: WXXML-FIX-STRING returned "foo&#13;bar&#13;"
```
so I guess the problem is that the XML is not being displayed as expected.

I haven't tried it on any other platform, so I don't know if it is specific to macOS.

**Comment by Parlazo** [comment]
wxMaxima version: 20.06.6_MSW_OpenMP201511+Locks
using wxWidgets version: wxWidgets 3.1.3
Maxima version: 5.44.0
Maxima build date: 2020-06-08 22:46:53
Host type: x86_64-w64-mingw32
System type: Win32 6.1.7601 (Service Pack 1) X86-64
Lisp implementation type: SBCL
Lisp implementation version: 2.0.0

same problem here... in wxMaxima none of the suggestions above work
please fix this
i also have problem with tab character.

**Comment by Parlazo** [comment]
maybe this is also related to this bug
freshline(ostream);
newline(ostream);
does also not produce a new line
how ever a new mine in this style...
"line1
line2"
produce somehow a tab style display in wxMaxima like 
line1    line2
~%
~&
~t
do not work
how ever ~a and ~f is working
it seems as there would be a problem around the control characters... at least in windows

**Comment by robert-dodier** [comment]
I have tried it again with wxMaxima 24.08.0 (development version) + wxWidgets 2.3.5. + Ubuntu, and in these examples, I see a correct display. Can someone (@daute , @gunterkoenigsmann ?) check it on Windows? If so then we can close this ticket as fixed.

Examples I tried:
```
foo: "hello
there
world";
printf (true, "foo~%bar~%baz~%");
printf (false, "foo~%bar~%baz~%");
```
In each case, the result is displayed on multiple lines as expected.

**Comment by robert-dodier** [comment]
I tried it with wxMaxima 24.08.0 on Windows and unfortunately, the display is still incorrect -- multiline strings are displayed with all characters on one line. I wonder why the display is correct on Linux and incorrect on Windows. For the record, the wxWidgets version on both platforms is 3.2.5.

**Comment by daute** [comment]
I think I fixed it now on Windows and Linux. Escaping the newline or carriage return seems unnecessary - it works here on Linux and Windows without these lines.

**Comment by daute** [comment]
Closed in the latest release (24.11.0, relased a Windows installer too).
